[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "marvin_ros"
version = "0.1.0"
dependencies = [
    "torchaudio",
    "onnxruntime",
    "silero-vad",
    "pyaudio",
    "bleak==2.1.1",
    "fastapi==0.128.0",
    "gpiozero==2.0.1",
    "numpy==2.4.0",
    "opencv_python==4.8.1.78",
    "picamera2==0.3.31",
    "Pillow==12.1.0",
    "spidev==3.5",
    "st3215==0.4.0",
    "uvicorn==0.40.0",
    "python-socketio[asyncio_client]",
    "pydantic",
]

[project.optional-dependencies]
dev = [
  "ruff",
  "pyright",
  "pytest",
]

[tool.ruff]
target-version = "py311"
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]
ignore = ["E501"]

[tool.pyright]
pythonVersion = "3.11"
typeCheckingMode = "standard"
include = ["src"]
